API/app/artigos/__init__.py
from flask import Blueprint
artigos = Blueprint('artigos', __name__)

from . import views

API/app/artigos/views.py
# -*- coding: utf-8 -*-

from . import artigos
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required
from flask import Markup
from ..models import User, Role, User, Table, Service, Terminal, TerminalType, Order, Category, Icon, Product, Attribute, Location

from .forms import  FormArtigo, FormProcurarArtigo
from .. import db

@artigos.route('/')
@login_required
def index():
    form=FormProcurarArtigo()
    produtos = Product.query.all()
    cat = Category.query.all()
    
    lista=[]
    for Empregados in produtos:
        lista.append([Empregados.id, Empregados.name, str(str(Empregados.price) +"€"), Empregados.description])
    return render_template('view.html', header='Artigos', columns =["Id","Producto","Preço","Descrição"],rows= lista, tabletype="striped", objecto="Artigos", titulo ="Artigos", form=form)
    
    
@artigos.route('/edit<id>', methods=['GET','POST'])
@login_required
def edit(id):
    form=FormArtigo()
    produtos = Product.query.get(id)

    form.name.data = produtos.name
    form.description.data = produtos.description
    form.price.data = produtos.price
    form.submit.label.text="Editar"
    
    if form.validate_on_submit():
       form=FormArtigo()
       produtos.name = form.name.data
       produtos.description = form.description.data
       produtos.price = form.price.data

       db.session.commit()
       flash('Artigo Atualizado com sucesso')
       return redirect(url_for('artigos.index'))

    return render_template('criar.html', titulo="Editar Artigo", form=form) 
    
    
    
@artigos.route('/criar', methods=['GET', 'POST'])
@login_required
def criar():
    
    form=FormArtigo()
    produtos = Product.query.all()
    
    if form.validate_on_submit():
        name = form.name.data
        description = form.description.data
        price = form.price.data

        produtoName = Product.query.filter_by(name=name).first()
        if produtoName:
            flash("Este produto já existe")
        else:
            artigo = Product(name=name, price=price, description=description)
            db.session.add(artigo)
            db.session.commit()
            flash("Artigo criado com sucesso")
            return redirect(url_for('artigos.index'))

    return render_template('criar.html', titulo="Criar Artigo", form=form) 
   
@artigos.route('/delete<id>')
@login_required
def delete(id):
    produto = Product.query.get(id)
    db.session.delete(produto)
    db.session.commit()
    flash('Artigo Eleminado com Sucesso')
    return redirect(url_for('artigos.index'))
    

API/app/atributos/__init__.py
from flask import Blueprint

atributos = Blueprint('atributos', __name__)

from . import views

API/app/atributos/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required
from . import atributos
from ..models import User, Role, User,AttributeCategory, Table, Service, Terminal, TerminalType, Order, Category, Icon, Product, Attribute, Location
from .forms import FormAtributo, FormAttr
from ..models import User
from .. import db

@atributos.route('/', methods=['GET', 'POST'])
def index():

    a=AttributeCategory.query.all()
    lista=[]
    for Empregados in a:
        if Empregados.multipleChoice == 0:
            lista.append([Empregados.id, Empregados.name, "Nao tem"])
        else:
            lista.append([Empregados.id, Empregados.name, "Tem"])
        
    return render_template('atributoss.html', header='Empregado', columns =["id","Nome","Escolha Multípla"],rows= lista, tabletype="striped", objecto="Categoria de Atributos", titulo ="Categoria de Atributos")

@atributos.route('/view<id>')
@login_required
def cat(id):
    cat = Attribute.query.all()
    catName = AttributeCategory.query.get(id)
    lista = []
    
    for i in cat:
        if i.attributeCategoryId == int(id):
            lista.append([i.id, i.name, str(str(i.price)+"€")])
    

    return render_template('subAtributes.html', header="Atributos", columns =["Id","Nome","Preço"], rows =lista, tabletype="striped", objecto="Atributo",objecto2=catName.id,objecto3=catName.name, titulo =catName.name, objecto4=catName.multipleChoice, objecto5=len(lista))



@atributos.route('/criarsubThis<id>', methods=['POST', 'GET'])
@login_required
def criarsubThis(id):
    
    form = FormAttr()
    lista = []
    AttrCatAll = AttributeCategory.query.all()
    AttrCat = AttributeCategory.query.get(id)
    for k in AttrCatAll:
        lista.append([k.id, k.name])
    form.categoriaId.choices =lista
    form.categoriaId.default = AttrCat.id
    
    if form.validate_on_submit():
        nome = form.name.data
        price = form.price.data
        print("AQUI")
        categoria = form.categoriaId.data
        insertAtr = Attribute(name=nome, price=price, attributeCategoryId=categoria)
    
        db.session.add(insertAtr)
        db.session.commit()
        flash('Atributo  criada com sucesso.')
        return redirect(url_for('atributos.index'))
    form.process()
    return render_template('criar.html', titulo="Criar Atributo", form=form)




@atributos.route('/criar', methods=['GET', 'POST'])
def criar():
    form = FormAtributo()
    form.multipleChoice.choices =([0,"Não"], [1, "Sim"])
    if form.validate_on_submit():
        nome = form.name.data
        multipleChoice = form.multipleChoice.data
        insertCategoryAtr = AttributeCategory(name=nome, multipleChoice=multipleChoice)
    
        db.session.add(insertCategoryAtr)
        db.session.commit()
        flash('Categoria criada com sucesso.')
        return redirect(url_for('atributos.index'))
    return render_template('criar.html', titulo="Criar Categoria Atributo", form=form)


@atributos.route('/edit<id>', methods=['GET','POST'])
@login_required
def edit(id):
    form=FormAtributo()
    produtosAtr = AttributeCategory.query.get(id)
    
    form.multipleChoice.choices =([0,"Não"], [1, "Sim"])
    form.multipleChoice.default = produtosAtr.multipleChoice
    form.process()
    form.name.data = produtosAtr.name
    form.submit.label.text="Editar"
    

    if form.validate_on_submit():
       form=FormAtributo()
       produtosAtr.name = form.name.data
       produtosAtr.multipleChoice = form.multipleChoice.data


       db.session.commit()
       flash('Categoria de atributos Atualizado com sucesso')
       return redirect(url_for('atributos.index'))

    return render_template('criar.html', titulo="Editar Categorias Atributos", form=form)


@atributos.route('/delete<id>')
@login_required
def delete(id):
    atributo = AttributeCategory.query.get(id)

    allAtributos = Attribute.query.filter_by(attributeCategoryId = id).all()
    
    for i in allAtributos:
        db.session.delete(i)
        db.session.commit()
        
    db.session.delete(atributo)
    db.session.commit()
    flash('Atributo Categoria Eleminado com Sucesso')
    return redirect(url_for('atributos.index'))


@atributos.route('/editsub<id>', methods=['POST', 'GET'])
@login_required
def editsub(id):
    form=FormAttr()
    Atr = Attribute.query.get(id)
    lista = []
    AttrCat = AttributeCategory.query.all()
    for k in AttrCat:
        lista.append([k.id, k.name])
    
    
    form.categoriaId.choices =lista
    form.categoriaId.default = Atr.attributeCategoryId
    form.process()

    form.name.data = Atr.name
    form.price.data = Atr.price

    form.submit.label.text="Editar"
    

    if form.validate_on_submit():
       form=FormAttr()
       Atr.name = form.name.data
       Atr.price = form.price.data
       Atr.attributeCategoryId = form.categoriaId.data

       db.session.commit()
       flash('Atributos Atualizado com sucesso')
       return redirect(url_for('atributos.index'))

    return render_template('criar.html', titulo="Editar Atributos", form=form)


@atributos.route('/deletesub<id>')
@login_required
def deletesub(id):
    atributo = Attribute.query.get(id)
    db.session.delete(atributo)
    db.session.commit()
    flash('Atributo  Eleminado com Sucesso')
    return redirect(url_for('atributos.index'))

API/app/categorias/__init__.py
from flask import Blueprint
categorias = Blueprint('categorias', __name__)

from . import views

API/app/categorias/views.py
# -*- coding: utf-8 -*-

from sqlalchemy import func
from sqlalchemy import text
from flask import Markup
from sqlalchemy import and_
from . import categorias
from ..models import User, Role, User, Table, Service, Terminal, TerminalType, Order, Category, Icon, Product, Attribute, Location
from flask_login import login_user, logout_user, login_required
from .. import db
from flask import render_template, redirect, request, url_for, flash
import datetime
from sqlalchemy import extract 
from collections import Counter
from .forms import CriarCategoria, SubCriarCategoria


#CATEGORIAS
@categorias.route('/')
@login_required
def index():
    cat = Category.query.all()
    lista=[]
    lista2=[]
    for i in cat:
        if i.level == 0:
            lista.append([i.id, i.name, i.description,"Principal"])
             
    return render_template('categorias.html', header="Categorias Principais", columns =["Id","Nome","Descrição","Categoria"], rows =lista, tabletype="striped", objecto="categorias", titulo ="Categorias")


@categorias.route('/view<id>')
@login_required
def cat(id):
    cat = Category.query.all()
    catName = Category.query.get(id)
    lista = []
    
    for i in cat:
        if i.categoryId == int(id):
            lista.append([i.id, i.name, "Secundária"])

    return render_template('subCategories.html', header="Categorias Secundárias", columns =["Id","Nome", "Categoria"], rows =lista, tabletype="striped", objecto="Sub Categoria",objecto2=catName.name, titulo =catName.name)


@categorias.route('/criar', methods=['GET', 'POST'])
@login_required
def criar():
    
    cat = Category.query.all()
    icons = Icon.query.all()
    form = CriarCategoria()
  
    if request.method == 'POST':
        data = request.form
        name = data.get("nome")
        description = data.get("descricao")
        iconId = data.get('icon')
        nameEng = data.get('name')
        descriptionEng = data.get('description')
        icons2 = Icon.query.filter_by(id=iconId).first()

        insertCategory = Category(name=name, description = description, level = 0, icons=[icons2])

        db.session.add(insertCategory)
        db.session.commit()
        flash('Categoria Criada com sucesso !')
        return redirect(url_for('categorias.index'))

    return render_template('criar_categorias.html', titulo="Criar Categoria",  iconsList=icons, form=form)


@categorias.route('/edit<id>', methods=['POST', 'GET'])
@login_required
def edit(id):
    
    form = CriarCategoria()
    icons = Icon.query.all()
    cat = Category.query.get(id)
    lol = cat.icons
    imageLoc = ""
    for i in lol:
        imageLoc = i.imageLocation

    if request.method == 'POST':
        cat = Category.query.get(id)
        data = request.form
        name = data.get("nome")
        description = data.get("descricao")
        iconId = data.get('icon')
        nameEng = data.get('name')
        descriptionEng = data.get('description')
        icons2 = Icon.query.filter_by(id=iconId).first()
        
        
        cat.name = name
        cat.description = description
        cat.icons = [icons2]
        
        db.session.commit()
        
        flash('Categoria Atualizada com sucesso ! ')
        return redirect(url_for('categorias.index'))
    
    return render_template('editar_categoria.html', titulo="Editar Categoria",iconsList=icons,name=cat.name,description=cat.description,iconS=imageLoc,idIn=id,form = form)

@categorias.route('/delete<id>', methods = ['GET','POST'])
@login_required
def delete(id):
 
    data=Category.query.get(id)
    db.session.delete(data)
    db.session.commit()

    flash("Categoria Apagada com Sucesso")
    
    return redirect(url_for('categorias.index'))



#SUB CATEGORIAS
@categorias.route('/editsub<id>', methods=['POST', 'GET'])
@login_required
def editSub(id):

   
    form = SubCriarCategoria()
    cat = Category.query.all()
    cat2 = Category.query.get(id)
    cat3 = Category.query.filter_by(id = cat2.categoryId).first()
    lista = []

    for i in cat:
        if i.level == 0:
            lista.append([i.id, i.name])


    form.categoryId.choices = lista
    form.categoryId.default = cat3.id
    form.process()
    
    form.name.data = cat2.name
    form.description.data = cat2.description
    
    

    if form.validate_on_submit():
        form = SubCriarCategoria()
        cat2.name = form.name.data
        cat2.description = form.description.data
        cat2.categoryId = form.categoryId.data

        db.session.commit()
        flash('Sub Categoria Atualizada com sucesso ! ')
        return redirect(url_for('categorias.index'))

    return render_template('criar.html', titulo="Editar Sub Categoria", form = form)



@categorias.route('/criarsub', methods=['POST', 'GET'])
@login_required
def criarSub():

    form = SubCriarCategoria()
    cat =   Category.query.all()
    lista = []
    for i in cat:
        if i.level == 0:
            lista.append([i.id, i.name])
    
    form.categoryId.choices = lista

    if request.method == 'POST' and form.validate():
        name = form.name.data
        description = form.description.data
        category = form.categoryId.data

        insertCategory = Category(name=name, description = description, level = 1, categoryId=category)
        db.session.add(insertCategory)
        db.session.commit()
        flash('Sub Categoria Criada com sucesso !')
        return redirect(url_for('categorias.index'))
   

    return render_template('criar.html', titulo="Criar Sub Categoria", form = form)


@categorias.route('/criarsubThis<nome>', methods=['POST', 'GET'])
@login_required
def criarsubThis(nome):
    
    form = SubCriarCategoria()
    cat2 = Category.query.all()
    lista = []

    for i in cat2:
        if i.name == nome:
            lista.append([i.id, i.name])

    form.categoryId.choices = lista

    if request.method == 'POST' and form.validate():
        name = form.name.data
        description = form.description.data
        category = form.categoryId.data

        insertCategory = Category(name=name, description = description, level = 1, categoryId=category)
        db.session.add(insertCategory)
        db.session.commit()
        flash('Sub Categoria Criada com sucesso !')
        return redirect(url_for('categorias.index'))
   

    return render_template('criar.html', titulo="Criar Sub Categoria", form = form)

API/app/encaminhamento/__init__.py
from flask import Blueprint
encaminhamento = Blueprint('encaminhamento', __name__)

from . import views

API/app/fam_atributos/__init__.py
from flask import Blueprint
fam_atributos = Blueprint('fam_atributos', __name__)

from . import views

API/app/fam_atributos/views.py
from . import fam_atributos
from flask import render_template, redirect, request, url_for, flash
from flask_login import login_user, logout_user, login_required
from flask import Markup
from ..models import User, Role, User, Table, Service, Terminal, TerminalType, Order, Category, Icon, Product, Attribute, Location

from .forms import  Fam_atributos, Atributos
from .. import db

@fam_atributos.route('/')
@login_required
def index():
    fams_atributos=Fam_Caracterisitica.query.all()
    lista=[]
    for Empregados in fams_atributos:
        
        
        lista.append([Empregados.id, Empregados.name, Empregados.tipo.name])
    
    return render_template('fam_atributos.html', header='Atributos', columns =["Id","Atributo", "Tipo"],rows= lista, tabletype="striped", objecto="fam_atributos", objectos="/fam_atributos/")

@fam_atributos.route('/<id>')
@login_required
def atributos(id):
    #atributos=Caracterisitica.query.filter_by(id_fam_caracteristica=id)
    
    atributos=Fam_Caracterisitica.query.options(db.joinedload('caracteristicas')).filter_by(id=id).first()
    lista=[]
    for Empregados in atributos.caracteristicas: 
        
        
        lista.append([Empregados.id, Empregados.name])
    
    return render_template('atributos.html', header='Atributos - '+str(atributos.name), columns =["Id","Atributo",""],rows= lista, tabletype="striped", objecto="fam_atributos", objectos="/fam_atributos/", id=id)    


@fam_atributos.route('/criar', methods=['GET', 'POST'])
@login_required
def criar_fam_atributos():
    form=Fam_atributos()
    tipo_atributos=Tipo_Caracterisitica.query.all()
    form.tipo.choices = [(g.id, g.name) for g in tipo_atributos]
    if form.validate_on_submit():
        tipo = form.tipo.data
        print(form.tipo.choices)
        fam= Fam_Caracterisitica(name=form.name.data, id_tipo_caracteristica=tipo)
        db.session.add(fam)
        db.session.commit()
        return redirect(url_for('fam_atributos.index'))
        
        
    return render_template('fam_atributos_criar.html', form=form)


@fam_atributos.route('/criar<id>',methods=['GET', 'POST'])
@login_required
def criar_atributos(id):
    form=Atributos()
    if form.validate_on_submit():
        atributo = Caracterisitica(id_fam_caracteristica= id, name =form.name.data)
        db.session.add(atributo)
        db.session.commit()
        return redirect(url_for('fam_atributos.atributos', id=id))
    return render_template('atributos_criar.html', form=form, id =id)
  

API/app/pedidos/__init__.py
from flask import Blueprint
pedidos = Blueprint('pedidos', __name__)

from . import views

API/app/templates/artigo.html
{% extends 'baseFrontHF.html' %}
{% from "macrosFront.html" import generatebreadCrumbs %}
{% from "macrosFront.html" import generateTitleDescription %}
{% from "macrosFront.html" import generateSeparator %}
{% from "macrosFront.html" import generateCartCounter %}
{% from "macrosFront.html" import generateAtributos %}
{% block head %}

    <script  src="{{ url_for('static', filename='js/single_artigo.js') }}"></script> 
    <script  src="{{ url_for('static', filename='js/favicon/all.min.js') }}"></script>   

{% endblock %} 
{% block title %}Artigo{% endblock %}
{% block body %}
    {{generatebreadCrumbs(breadCrumbs)}}

    {{generateTitleDescription(info)}}
 
 
    <!-- method="POST" action="{{redirect}}" -->
    </div>
    <form artigo-id="{{id}}" id="pedido-form" class="options-form" action="{{redirect}}" method="POST">
        <input type="text" style="display: none;" name="product-id" value="{{id}}">
        <input type="text" style="display: none;" name="product-category-level-0-id" value="{{categoryLevel0}}">

        {{generateAtributos(atributos)}}
    
    <div class="container" style="{% if allowObs == false %} display=none {% endif %}">
        <div class="row obs-holder">
            <div class="col">
                <input class="fatu-input" id="observacoes" placeholder="observações" name="obs" type="text">
            </div>
        </div>

        <div class="row qnt-row">
            <div class="col">
                <div class="qnt-holder">
                    <div class="minus qnt-icon">
                        <i class="fas fa-minus"></i>
                    </div>
                    <input min="1" class="input-qnt" disabled type="text" pattern="[0-9]+" name="qnt" value="1">
                    <div class="plus qnt-icon">
                        <i class="fas fa-plus"></i>
                    </div>
                </div>
            </div>
        </div>

        
        <div class="row">
            <div class="col">
                <input disabled style="opacity: 0.6;" class="pedir-btn" type="submit" value="adicionar">
            </div>
        </div>
    </div>
</form> 
{% endblock %}

{% block ordersCounter %}
    {{generateCartCounter(ordersCounter)}}     
{% endblock %}

{% block cartUrl %}
    {{cartUrl}}
{% endblock %}
{% block pagamentoUrl %} 
    {{pagamentoUrl}}
{% endblock %}

API/app/templates/atributos.html
{% extends "base.html" %}
{% from "macros.html" import table %}
{% from "macros.html" import crud %}



{% block titulo_content %}
<h1 class="page-header">Atributos</h1>
{% endblock %}

{% block page_content %}


<p>

<a href="{{ url_for('fam_atributos.criar_atributos', id=id) }}"><button type="button" class="btn btn-primary">Criar Atributo</button></a>

</p>



  

{{ crud(header, columns, rows, tabletype, objecto, objectos, context = None) }} 
  

                                   
                            
                      

{% endblock %}

API/app/templates/atributos_criar.html
{% extends "base.html" %}


{% import "bootstrap/wtf.html" as wtf %}


{% block titulo_content %}
<h1 class="page-header">Criar Atributos</h1>
{% endblock %}

{% block page_content %}

{{ wtf.quick_form(form) }}
<a href="{{ url_for('fam_atributos.index') }}"><button type="button" class="btn btn-primary">Cancelar</button></a>
                        
                            
                      

{% endblock %}

API/app/templates/avaliacao.html
{% extends 'baseFrontHF.html' %}
{% from "macrosFront.html" import generatebreadCrumbs %}

{% block head %}
<script  src="{{ url_for('static', filename='js/favicon/all.min.js') }}"></script>   
<script  src="{{ url_for('static', filename='js/starRating.js') }}"></script>   


<script  src="{{ url_for('static', filename='js/rate.js') }}"></script>   
<script  src="{{ url_for('static', filename='js/iconfont.js') }}"></script>   

{% endblock %} 
{% block title %}Avaliação{% endblock %}
{% block body %}
    {{generatebreadCrumbs(breadCrumbs)}}
    <div class="container">
        <div class="row">
            <div class="col">
                <div id="rateBox"></div>
            </div>
        </div>
    </div>
{% endblock %}

API/app/templates/carrinho.html
{% extends 'baseFrontHF.html' %}
{% from "macrosFront.html" import generatebreadCrumbs %}
{% from "macrosFront.html" import generateCartCounter %}
{% from "macrosFront.html" import  generateHeaderImage %}
{% from "macrosFront.html" import  generateCarrinho %}
{% block head %}
    <script  src="{{ url_for('static', filename='js/carrinho.js') }}"></script>
    <script  src="{{ url_for('static', filename='js/favicon/all.min.js') }}"></script>   
{% endblock %}
{% block title %}Carrinho{% endblock %}


{% block body %}
    <span style="display: none;" id="pagamento" pagamentoUrl="{{pagamentoUrl}}"></span>
    {{generatebreadCrumbs(breadCrumbs)}}

    {{generateHeaderImage(headerImageContent)}}

    {{generateCarrinho(orders)}}


{% endblock %}

{% block ordersCounter %}
    {{generateCartCounter(ordersCounter)}}     
{% endblock %}

{% block cartUrl %}
    {{cartUrl}}
{% endblock %}
{% block pagamentoUrl %} 
    {{pagamentoUrl}}
{% endblock %}

API/app/templates/categorias.html
{% extends "base.html" %}
{% from "macrosCategory.html" import crud %}

{% block titulo_content %}
<h1 class="page-header">{{titulo}}</h1>
{% endblock %}

{% block page_content %}


<p>
<a href="criar"><button type="button" class="btn btn-primary">Criar {{objecto}}</button></a>
<a href="criarsub"><button type="button" class="btn btn-primary">Criar Subcategoria</button></a>
    
</p>

{{ crud(header, columns, rows, tabletype, objecto, context = None) }}  

  

{% endblock %}

API/app/templates/criar_artigo.html
{% extends "base.html" %}
{% from "macros.html" import table %}
{% from "macros.html" import tab %}

{% block titulo_content %}
<h1 class="page-header">Criar Artigo</h1>
{% endblock %}

{% block page_content %}
<form method = "POST" action = "{{ url_for('artigos.criar') }}">
<input type="hidden" name="proxima" value="{{ proxima or url_for('artigos.index') }}">
<div class="col-lg-7">
<div class="form-group">
<form role="form">
                                                    <label>Nome</label>
                                                    <input class="form-control"  name="nome">
                                                    
                                                </div>
                                                    <div class="form-group">
                                                    <label>Serviço</label>
                                                    <select <input class="form-control" name="servico">
                                                    {% for servico in servicos %}
                                                    <option value={{servico.id}}>{{servico.name}}</option>
                                                    {% endfor %}
                                                        
                                                    </select>
                                                </div>
                                                
                                                <div class="form-group">
                                                    <label>Descrição</label>
                                                    <input class="form-control" name="trdddnadora">
                                              
                                                </div>
                                                <div class="form-group">
                                                    <label>Text Inrrrput</label>
                                                    <input class="form-control" name="tnadora">
                                                  
                                                </div>
                                                    <div class="form-group">
                                                    <label>Serviço</label>
                                                    <select <input class="form-control" name="tddora">
                                                        <option>1</option>
                                                        <option>2</option>
                                                        <option>3</option>
                                                        <option>4</option>
                                                        <option>5</option>
                                                    </select>
                                                </div>

</div> 
<div class="col-lg-5">
  
{{ tab(header, items) }}
                                   
</div>                           
  <div class="col-lg-12">
   
    <input type="submit" value="Criar" class="btn btn-default"/>
    </form>  
  </div>
  
                   
</div>
{% endblock %}

API/app/templates/criar_encaminhamento.html
{% extends "base.html" %}
{% from "macros.html" import table %}
{% import "bootstrap/wtf.html" as wtf %}

{% block titulo_content %}
<h1 class="page-header">Criar Encaminhamento</h1>
{% endblock %}

{% block page_content %}





{{ wtf.quick_form(form) }}


                                   
                            
                      

{% endblock %}

API/app/templates/criar_menus.html
{% extends "base.html" %}
{% from "macros.html" import table %}
{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}

<style>
    [type=radio] { 
position: absolute;
opacity: 0;
width: 0;
height: 0;
}

/* IMAGE STYLES */
[type=radio] + img {
cursor: pointer;
}

/* CHECKED STYLES */
[type=radio]:checked + img {
outline: 3px solid #ffaa22;

}





</style>
<h1 class="page-header">{{titulo}}</h1>

   


<form method = "POST" name="actorInsert" action = "{{ url_for('menus.criar') }}" onSubmit="return ValidateActInsert()">
    

    <div class="col-lg-7">
        <div style="display: flex;">
        <div class="form-group" style="width: 400px;">
            <form role="form">
                <label>Nome</label>
                <input class="form-control"  name="nome" maxlength="64" required title="Maximo 64 caracteres">
        </div>
       
        </div>
            
        <div class="form-group">
       
            {% for i in categoriasLista %}
            <input type="checkbox" id="{{i[0]}}" name="cat" value="{{i[0]}}">
            <label for="cat">{{i[1]}} </label><br><br>
            {% endfor %}
        
      </div>
      </div>
 
    <br>
    <div class="col-lg-12">
        {{form.csrf_token}}
        <input type="submit" value="Criar" class="btn btn-default"/>
        
        </form>  
      </div>
    </div>

  

{% endblock %}

API/app/templates/fam_artigos.html
{% extends "base.html" %}
{% from "macros.html" import table %}
{% from "macros.html" import crud %}



{% block titulo_content %}
<h1 class="page-header">Categorias</h1>
{% endblock %}

{% block page_content %}


<p>
<button type="button" class="btn btn-primary">Nova Categoria</button>

</p>



  

{{ crud(header, columns, rows, tabletype, objecto,objectos, context = None) }} 
  

                                   
                            
                      

{% endblock %}

API/app/templates/restaurante.html
{% extends 'baseFront.html' %}
{% block head %}
{{ super() }}
    <script src="{{ url_for('static', filename='js/redirect.js') }}"></script>
{% endblock %}
{% block title %}Restaurante{% endblock %}
{% block body %}
    <body >
        <span style="display: none;" id="menuUrl" menuUrl="{{menuUrl}}"></span>
        <div class="vertical-center">
            <div class="container splash">
                <div class="row justify-content-md-center"> 
                    <div class="col">
                        <div class="image-holder">
                            <div class="background" style="background: url('{{imageUrl}}');"></div>
                        </div> 
                    </div>
                    
                </div>
                
                <div class="row justify-content-md-center"> 
                    <div class="col">
                        <div class="text-holder">
                            <h2>Bem-vindo ao restaurante <br>{{name}}</h2>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-md-center"> 
                    <div class="col">
                        <div class="gif-holder">
                            
                            <img src="{{ url_for('static', filename='images/Untitled2.gif') }}">
                        </div>
                    </div>
                </div>

                
            </div>
        </div>
{% endblock %}

API/app/templates/terminal_empregado.html
{% extends "base.html" %}
{% from "macros.html" import table %}

{% block titulo_content %}
<h1 class="page-header">Terminal Empregado</h1>
{% endblock %}

{% block page_content %}





{{ table(header, columns, rows, tabletype, context = None) }}   

                                   
                            
                      

{% endblock %}